# Thomas Serafin - Numpy basic pratice 

Notes 

 Why Numpy over Lists
 1. numpy is faster than lists because it reads less bytes of memory
 2. no type checking when iterating through objects
 3. Contiguous Memory (A) SMID Vector Processign (2) Effective Cache Utilization
 
 In my opinion, "Matlab replacement". Doing Matlab in Python. 

In [5]:
import numpy as np

In [2]:
a = np.array([1,3,5])
b = np.array([1,2,3])
print(a * b)

[ 1  6 15]


In [12]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

a = np.array([1,3,5], dtype = 'int16') # changing type in order to take up less size 


[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
# getting the dimension 
b.ndim

2

In [14]:
# Getting Shape
a.shape
b.shape

(2, 3)

In [15]:
# Get type 
a.dtype

dtype('int16')

In [17]:
# Getting size 
# if I changed dtype to int64 i would be have 4 bytes, 2x larger 
a.itemsize

2

In [19]:
# Get totalsize 
a.nbytes

6

Accessing/Changing specific elements, rows, columns, etc

In [23]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [31]:
# get a specific element 
a[0] # getting the 1st row 
a[1, 6] # getting a specific value 
a[1,-2]

13

In [34]:
# get a full row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [36]:
# More fancy [startindex:endindex:stepsize]
a[0, 1:6:2] # elements 1 to 6 but step by 2 

array([2, 4, 6])

In [37]:
# changing element
a[1,5] = 20 
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [39]:
# Replacing a column 
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

Initializing Different Types of Arrays

In [47]:
# all zero matrix
np.zeros(4)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
# All 1s matrix
np.ones(4)

array([1., 1., 1., 1.])

In [50]:
np.full((2,2), 55) # first is size and then values 

array([[55, 55],
       [55, 55]])

In [51]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [52]:
# random decimal numbers
np.random.rand(4,2)

array([[0.95583725, 0.3782749 ],
       [0.82444905, 0.9790837 ],
       [0.3172757 , 0.82093105],
       [0.83902717, 0.21604112]])

In [53]:
# similar shape but now random
np.random.random_sample(a.shape)

array([[0.43427072, 0.09971184, 0.30172457, 0.48855188, 0.94882891,
        0.54913802, 0.83215086],
       [0.33887639, 0.72918447, 0.0701979 , 0.22715078, 0.23443758,
        0.02331549, 0.6852113 ]])

In [57]:
# random integer values
np.random.randint(1,7, size = (3,3)) # range, size 

array([[3, 3, 1],
       [3, 5, 3],
       [4, 4, 1]])

In [60]:
# repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [62]:
# or this 
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
# pratice 
a1 = np.ones([5,5], dtype = "int16")
a1[1:4, 1:4] = 0
a1[2,2] = 9
a1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [75]:
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9 

output[1:4, 1:4] = z
#output[1:-1, 1:-1] = z # same thing above except, saying first to last element for each row & column 

output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
# When copying arrays, use e.g. a.copy() in order to copy contents 

Mathematics

In [78]:
c = np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [80]:
c + 2 

array([3, 4, 5, 6])

In [81]:
a - 2 

array([[-1,  0,  3,  2,  3,  4,  5],
       [ 6,  7,  3,  9, 10, 18, 12]])

a * 2 

In [83]:
a / 2 

array([[ 0.5,  1. ,  2.5,  2. ,  2.5,  3. ,  3.5],
       [ 4. ,  4.5,  2.5,  5.5,  6. , 10. ,  7. ]])

Linear Algebra


In [85]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [87]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

Statistics

In [88]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
# min value
np.min(stats)


1

In [93]:
np.max(stats)

6

In [94]:
np.sum(stats) # sum of all the elements 

21

Reorganizing Arrays

In [96]:
# you can reshape 

# vertical stacking below 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,3))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.]])

Extras 

In [ ]:
# loading data from textfile or excel in numpy. 
filedata = np.genfromtxt('name_of_file.txt', delimiter=',')
filedata = filedata.astype('int32')


#### Advanced Indexing

In [ ]:
# Find where in our file data is greater than 50
filedata > 50 
filedata[filedata > 50]

# can also pass through a list to index
filedata[[list]]


np.any(filedata > 50, axis = 0 ) # another thing would be np.all 


In [ ]:
# multiple conditions
((filedata >50) % (fieldata < 100))
(~(filedata >50) % (fieldata < 100))


#### Extra stuff

In [8]:
# How to get common items between two numpy arrays 
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [10]:
np.intersect1d(a,b)

array([2, 4])

In [12]:
# How to convert all elements into uppercase example 
import pandas as pd
ser = pd.Series(['mary', 'had','a','little','lamb'])
ser

0      mary
1       had
2         a
3    little
4      lamb
dtype: object

In [13]:
ser = ser.map(lambda x: x.title())

In [14]:
ser

0      Mary
1       Had
2         A
3    Little
4      Lamb
dtype: object

In [15]:
# getting the length of each
ser.map(lambda a:len(a))

0    4
1    3
2    1
3    6
4    4
dtype: int64

In [ ]:
# how to do linear regression with training and testing data
boston = pd.read_csv("test_data.csv")

x = pd.DataFrame(boston['rm']) # features
y = pd.DataFrame(boston['medv']) # target

# splitting into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2)

# building the model 
from sklearn.learn_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

# predicting the values
y_pred = regressor.predict(x_test)

from sklearn import metrics
import numpy as np
print('Root Mean Squared Error', np.sqrt(metrics.mean_squared_error(y_test, y_pred))
      
      

In [ ]:
# build a decision tree classifier model. use train/test split 70/30
iris = pd.read_csv('iris.csv')
x = pd.DataFrame(iris([['Speal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']]))
y = iris['Species']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

from sklearn.tree imnport DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)


from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import accuracy score
print(accuracy_score(y_test, y_pred))


#### Working with Big Data 

In [ ]:
# example 

new_df = pd.DataFrame(columns = df.columns)

for df in pd.read_csv("dataset.csv", chunksize = 5):
    results = df.groupby(['Type 1']).count()
    
    new_df = pd.concat([new_df, results])

